#
# General settings
#
command_character: "."
insult: "you're a faggot"

#
# Redis Settings
#
redis_prefix: markov

#
# IRC Settings
#
irc_ssl: true
irc_server: irc.foo.bar
irc_port: 6697
irc_channel: "#baz"
irc_nickname: shithead-ng
irc_nickname2: shithead
