#
# General settings
#
command_character: "."

#
# Redis Settings
#
redis_prefix: markov

#
# IRC Settings
#
irc_server: irc.foo.bar
irc_port: 6667
irc_channel: "#baz"
irc_nickname: shithead-ng
irc_nickname2: shithead
