#
# General settings
#
command_character: "."
insult: ""
insult_chance: 0 # % chance that the bot will use the insult
                 # can be 0 to disable insults
target_words: 4 # lowest number of words in an 'ideal' response
respond_on_highlight: true

#
# Redis Settings
#
redis_prefix: markov
redis_server: 127.0.0.1:6379
redis_usepass: false
redis_password: hunter2

#
# IRC Settings
#
irc_ssl: true
irc_server: irc.foo.bar
irc_port: 6697
irc_nickname: shithead-ng
irc_nickname2: shithead
irc_channels:
  - "#foo"
  - "#bar"
  - "#baz"
# irc_password: hunter2

#
# RNG to use
# This can be "rand" for perl's built in rand() function
# Or "mt" to use the Math::Random::MT::Perl module (recommended)
#
rng: rand
