#
# General settings
#
command_character: "."
insult: "you're a faggot"

#
# Redis Settings
#
redis_prefix: markov
redis_server: 127.0.0.1:6379
redis_usepass: false
redis_password: hunter2

#
# IRC Settings
#
irc_ssl: true
irc_server: irc.foo.bar
irc_port: 6697
irc_channel: "#baz"
irc_nickname: shithead-ng
irc_nickname2: shithead

#
# RNG to use
# This can be "rand" for perl's built in rand() function
# Or "mt" to use the Math::Random::MT::Perl module (recommended)
#
rng: rand
